# Generated by Django 6.0.2 on 2026-02-25 10:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"ordering": ["last_name", "first_name"]},
        ),
        migrations.AlterModelOptions(
            name="teacher",
            options={"ordering": ["last_name", "first_name"]},
        ),
        migrations.RenameField(
            model_name="student",
            old_name="grade",
            new_name="class_name",
        ),
        migrations.AddField(
            model_name="student",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="student",
            name="emergency_contact",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="emergency_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="student",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Masculin"), ("F", "Féminin"), ("O", "Autre")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="medical_info",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="student",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\+?1?\\d{9,15}$", "Numéro de téléphone invalide"
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="student_photos/"),
        ),
        migrations.AddField(
            model_name="student",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Actif"),
                    ("inactive", "Inactif"),
                    ("graduated", "Diplômé"),
                    ("suspended", "Suspendu"),
                ],
                default="active",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="experience_years",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="teacher",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Masculin"), ("F", "Féminin"), ("O", "Autre")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="teacher_photos/"),
        ),
        migrations.AddField(
            model_name="teacher",
            name="qualification",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="teacher",
            name="salary",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Actif"),
                    ("inactive", "Inactif"),
                    ("on_leave", "En congé"),
                ],
                default="active",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\+?1?\\d{9,15}$", "Numéro de téléphone invalide"
                    )
                ],
            ),
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("description", models.TextField(blank=True)),
                ("credits", models.PositiveIntegerField(default=1)),
                ("course_grade", models.CharField(max_length=50)),
                ("schedule", models.CharField(blank=True, max_length=200)),
                ("max_students", models.PositiveIntegerField(default=30)),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="school.teacher",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade_value", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "max_grade",
                    models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
                ),
                ("exam_date", models.DateField()),
                ("comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_grades",
                        to="school.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_grades",
                        to="school.student",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="school.teacher"
                    ),
                ),
            ],
            options={
                "ordering": ["-exam_date"],
            },
        ),
        migrations.CreateModel(
            name="StudentTeacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enrollment_date", models.DateField(auto_now_add=True)),
                ("grade", models.CharField(blank=True, max_length=5)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="school.course"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="school.student"
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="school.teacher"
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "teacher", "course")},
            },
        ),
        migrations.AddField(
            model_name="student",
            name="assigned_teachers",
            field=models.ManyToManyField(
                blank=True, through="school.StudentTeacher", to="school.teacher"
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="assigned_students",
            field=models.ManyToManyField(
                blank=True, through="school.StudentTeacher", to="school.student"
            ),
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Présent"),
                            ("absent", "Absent"),
                            ("late", "En retard"),
                            ("excused", "Excusé"),
                        ],
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="school.student"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="school.course"
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("student", "course", "date")},
            },
        ),
    ]
